# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tomas/OneDrive/Dokumenty/GitHub/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/ip/start_memblock/start_memblock.xci
# IP: The module: 'start_memblock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tomas/OneDrive/Dokumenty/GitHub/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/ip/start_memblock/start_memblock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'start_memblock'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/tomas/OneDrive/Dokumenty/GitHub/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/ip/start_memblock/start_memblock.xci
# IP: The module: 'start_memblock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tomas/OneDrive/Dokumenty/GitHub/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/ip/start_memblock/start_memblock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'start_memblock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
