# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.cache/wt [current_project]
set_property parent.project_path D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/TabledAsymetricNumeralSystems/Licencjat2.0/Licencjat2.0/start.coe
add_files -quiet d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/ip/start_memblock/start_memblock.dcp
set_property used_in_implementation false [get_files d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/ip/start_memblock/start_memblock.dcp]
read_vhdl -library xil_defaultlib {
  D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/new/Serializator.vhd
  D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/new/nbRom.vhd
  D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/new/startRom.vhd
  D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/new/Decoder.vhd
  D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/new/nbBitsRomDecoder.vhd
  D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/new/newXRomDecoder.vhd
  D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/new/symbolRomDecoder.vhd
  D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/new/encodingTableRom.vhd
  D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/start_block/hdl/start_block_wrapper.vhd
  D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/nb_block/hdl/nb_block_wrapper.vhd
  D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/encoding_table_block/hdl/encoding_table_block_wrapper.vhd
  D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_in_block/hdl/data_in_block_wrapper.vhd
  D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_out_block/hdl/data_out_block_wrapper.vhd
  D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/new/Compressor.vhd
  D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/new/Driver.vhd
  D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/new/Encoder.vhd
}
add_files D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/start_block/start_block.bd
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/start_block/ip/start_block_blk_mem_gen_0_0/start_block_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/start_block/ip/start_block_axi_bram_ctrl_0_0/start_block_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/start_block/ip/start_block_processing_system7_0_0/start_block_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/start_block/ip/start_block_rst_ps7_0_50M_0/start_block_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/start_block/ip/start_block_rst_ps7_0_50M_0/start_block_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/start_block/ip/start_block_rst_ps7_0_50M_0/start_block_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/start_block/ip/start_block_auto_pc_0/start_block_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/start_block/start_block_ooc.xdc]
set_property is_locked true [get_files D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/start_block/start_block.bd]

add_files D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/nb_block/nb_block.bd
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/nb_block/ip/nb_block_processing_system7_0_0/nb_block_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/nb_block/ip/nb_block_blk_mem_gen_0_0/nb_block_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/nb_block/ip/nb_block_axi_bram_ctrl_0_0/nb_block_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/nb_block/ip/nb_block_rst_ps7_0_50M_0/nb_block_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/nb_block/ip/nb_block_rst_ps7_0_50M_0/nb_block_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/nb_block/ip/nb_block_rst_ps7_0_50M_0/nb_block_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/nb_block/ip/nb_block_auto_pc_0/nb_block_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/nb_block/nb_block_ooc.xdc]
set_property is_locked true [get_files D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/nb_block/nb_block.bd]

add_files D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/encoding_table_block/encoding_table_block.bd
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/encoding_table_block/ip/encoding_table_block_processing_system7_0_0/encoding_table_block_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/encoding_table_block/ip/encoding_table_block_blk_mem_gen_0_0/encoding_table_block_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/encoding_table_block/ip/encoding_table_block_axi_bram_ctrl_0_0/encoding_table_block_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/encoding_table_block/ip/encoding_table_block_rst_ps7_0_50M_0/encoding_table_block_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/encoding_table_block/ip/encoding_table_block_rst_ps7_0_50M_0/encoding_table_block_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/encoding_table_block/ip/encoding_table_block_rst_ps7_0_50M_0/encoding_table_block_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/encoding_table_block/ip/encoding_table_block_auto_pc_0/encoding_table_block_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/encoding_table_block/encoding_table_block_ooc.xdc]
set_property is_locked true [get_files D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/encoding_table_block/encoding_table_block.bd]

add_files D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_in_block/data_in_block.bd
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_in_block/ip/data_in_block_processing_system7_0_0/data_in_block_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_in_block/ip/data_in_block_axi_bram_ctrl_0_0/data_in_block_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_in_block/ip/data_in_block_blk_mem_gen_0_0/data_in_block_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_in_block/ip/data_in_block_rst_ps7_0_50M_0/data_in_block_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_in_block/ip/data_in_block_rst_ps7_0_50M_0/data_in_block_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_in_block/ip/data_in_block_rst_ps7_0_50M_0/data_in_block_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_in_block/ip/data_in_block_auto_pc_0/data_in_block_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_in_block/data_in_block_ooc.xdc]
set_property is_locked true [get_files D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_in_block/data_in_block.bd]

add_files D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_out_block/data_out_block.bd
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_out_block/ip/data_out_block_blk_mem_gen_0_0/data_out_block_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_out_block/ip/data_out_block_axi_bram_ctrl_0_0/data_out_block_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_out_block/ip/data_out_block_processing_system7_0_0/data_out_block_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_out_block/ip/data_out_block_rst_ps7_0_50M_0/data_out_block_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_out_block/ip/data_out_block_rst_ps7_0_50M_0/data_out_block_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_out_block/ip/data_out_block_rst_ps7_0_50M_0/data_out_block_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_out_block/ip/data_out_block_auto_pc_0/data_out_block_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_out_block/data_out_block_ooc.xdc]
set_property is_locked true [get_files D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/data_out_block/data_out_block.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Compressor -part xc7z010clg400-1


write_checkpoint -force -noxdef Compressor.dcp

catch { report_utilization -file Compressor_utilization_synth.rpt -pb Compressor_utilization_synth.pb }
