# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/start_block/start_block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==start_block || ORIG_REF_NAME==start_block}]

# IP: bd/start_block/ip/start_block_blk_mem_gen_0_0/start_block_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==start_block_blk_mem_gen_0_0 || ORIG_REF_NAME==start_block_blk_mem_gen_0_0}]

# IP: bd/start_block/ip/start_block_axi_bram_ctrl_0_0/start_block_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==start_block_axi_bram_ctrl_0_0 || ORIG_REF_NAME==start_block_axi_bram_ctrl_0_0}]

# IP: bd/start_block/ip/start_block_processing_system7_0_0/start_block_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==start_block_processing_system7_0_0 || ORIG_REF_NAME==start_block_processing_system7_0_0}]

# IP: bd/start_block/ip/start_block_axi_mem_intercon_0/start_block_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==start_block_axi_mem_intercon_0 || ORIG_REF_NAME==start_block_axi_mem_intercon_0}]

# IP: bd/start_block/ip/start_block_rst_ps7_0_50M_0/start_block_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==start_block_rst_ps7_0_50M_0 || ORIG_REF_NAME==start_block_rst_ps7_0_50M_0}]

# IP: bd/start_block/ip/start_block_auto_pc_0/start_block_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==start_block_auto_pc_0 || ORIG_REF_NAME==start_block_auto_pc_0}]

# XDC: bd/start_block/start_block_ooc.xdc
