# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ZYBO_master.xdc

# Block Designs: bd/Memory/Memory.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory || ORIG_REF_NAME==Memory}]

# IP: bd/Memory/ip/Memory_axi_bram_ctrl_0_0/Memory_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Memory_axi_bram_ctrl_0_0}]

# IP: bd/Memory/ip/Memory_axi_bram_ctrl_1_0/Memory_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_axi_bram_ctrl_1_0 || ORIG_REF_NAME==Memory_axi_bram_ctrl_1_0}]

# IP: bd/Memory/ip/Memory_axi_bram_ctrl_2_0/Memory_axi_bram_ctrl_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_axi_bram_ctrl_2_0 || ORIG_REF_NAME==Memory_axi_bram_ctrl_2_0}]

# IP: bd/Memory/ip/Memory_axi_bram_ctrl_3_0/Memory_axi_bram_ctrl_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_axi_bram_ctrl_3_0 || ORIG_REF_NAME==Memory_axi_bram_ctrl_3_0}]

# IP: bd/Memory/ip/Memory_axi_bram_ctrl_4_0/Memory_axi_bram_ctrl_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_axi_bram_ctrl_4_0 || ORIG_REF_NAME==Memory_axi_bram_ctrl_4_0}]

# IP: bd/Memory/ip/Memory_axi_mem_intercon_0/Memory_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_axi_mem_intercon_0 || ORIG_REF_NAME==Memory_axi_mem_intercon_0}]

# IP: bd/Memory/ip/Memory_data_in_mem_0/Memory_data_in_mem_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_data_in_mem_0 || ORIG_REF_NAME==Memory_data_in_mem_0}]

# IP: bd/Memory/ip/Memory_data_out_mem_0/Memory_data_out_mem_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_data_out_mem_0 || ORIG_REF_NAME==Memory_data_out_mem_0}]

# IP: bd/Memory/ip/Memory_encoding_table_mem_0/Memory_encoding_table_mem_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_encoding_table_mem_0 || ORIG_REF_NAME==Memory_encoding_table_mem_0}]

# IP: bd/Memory/ip/Memory_nb_mem_0/Memory_nb_mem_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_nb_mem_0 || ORIG_REF_NAME==Memory_nb_mem_0}]

# IP: bd/Memory/ip/Memory_processing_system7_0_0/Memory_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_processing_system7_0_0 || ORIG_REF_NAME==Memory_processing_system7_0_0}]

# IP: bd/Memory/ip/Memory_rst_ps7_0_50M_0/Memory_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_rst_ps7_0_50M_0 || ORIG_REF_NAME==Memory_rst_ps7_0_50M_0}]

# IP: bd/Memory/ip/Memory_start_mem_0/Memory_start_mem_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_start_mem_0 || ORIG_REF_NAME==Memory_start_mem_0}]

# IP: bd/Memory/ip/Memory_xbar_0/Memory_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_xbar_0 || ORIG_REF_NAME==Memory_xbar_0}]

# IP: bd/Memory/ip/Memory_auto_pc_0/Memory_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Memory_auto_pc_0 || ORIG_REF_NAME==Memory_auto_pc_0}]

# XDC: bd/Memory/Memory_ooc.xdc
