set_property SRC_FILE_INFO {cfile:D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/constrs_1/new/ZYBO_master.xdc rfile:../../../KompresjaDanych.srcs/constrs_1/new/ZYBO_master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L16   IOSTANDARD LVCMOS33 } [get_ports { clk }];
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {enc/current_state[0]} -source [get_ports clk] -divide_by 2 [get_pins {enc/FSM_sequential_current_state_reg[0]/Q}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {enc/current_state[1]} -source [get_ports clk] -divide_by 2 [get_pins {enc/FSM_sequential_current_state_reg[1]/Q}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {enc/current_state[2]} -source [get_ports clk] -divide_by 2 [get_pins {enc/FSM_sequential_current_state_reg[2]/Q}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/FSM_onehot_current_state_reg_n_1_[0]} -source [get_ports clk] -divide_by 2 [get_pins {middle/FSM_onehot_current_state_reg[0]/Q}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/FSM_onehot_current_state_reg_n_1_[1]} -source [get_ports clk] -divide_by 2 [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/FSM_onehot_current_state_reg_n_1_[2]} -source [get_ports clk] -divide_by 2 [get_pins {middle/FSM_onehot_current_state_reg[2]/Q}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/FSM_onehot_current_state_reg_n_1_[3]} -source [get_ports clk] -divide_by 2 [get_pins {middle/FSM_onehot_current_state_reg[3]/Q}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/FSM_onehot_current_state_reg_n_1_[4]} -source [get_ports clk] -divide_by 2 [get_pins {middle/FSM_onehot_current_state_reg[4]/Q}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[0]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[0]/Q}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[1]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[1]/Q}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[2]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[2]/Q}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[3]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[3]/Q}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[4]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[4]/Q}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[5]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[5]/Q}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[6]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[6]/Q}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[7]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[7]/Q}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[8]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[8]/Q}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[9]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[9]/Q}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[10]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[10]/Q}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[11]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[11]/Q}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[12]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[12]/Q}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[13]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[13]/Q}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[14]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[14]/Q}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[15]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[15]/Q}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[16]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[16]/Q}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[17]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[17]/Q}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[18]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[18]/Q}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[19]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[19]/Q}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[20]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[20]/Q}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[21]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[21]/Q}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[22]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[22]/Q}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[23]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[23]/Q}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[24]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[24]/Q}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[25]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[25]/Q}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[26]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[26]/Q}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[27]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[27]/Q}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[28]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[28]/Q}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[29]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[29]/Q}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[30]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[30]/Q}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/amount[31]} -source [get_pins {middle/FSM_onehot_current_state_reg[1]/Q}] -divide_by 2 [get_pins {middle/amount_reg[31]/Q}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[0]} -source [get_pins {middle/counter_reg[0]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[0]/Q}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[0]_1} -source [get_pins {middle/counter_reg[0]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[0]/Q}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[10]} -source [get_pins {middle/counter_reg[10]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[10]/Q}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[10]_1} -source [get_pins {middle/counter_reg[10]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[10]/Q}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[11]} -source [get_pins {middle/counter_reg[11]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[11]/Q}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[11]_1} -source [get_pins {middle/counter_reg[11]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[11]/Q}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[12]} -source [get_pins {middle/counter_reg[12]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[12]/Q}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[12]_1} -source [get_pins {middle/counter_reg[12]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[12]/Q}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[13]} -source [get_pins {middle/counter_reg[13]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[13]/Q}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[13]_1} -source [get_pins {middle/counter_reg[13]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[13]/Q}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[14]} -source [get_pins {middle/counter_reg[14]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[14]/Q}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[14]_1} -source [get_pins {middle/counter_reg[14]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[14]/Q}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[15]} -source [get_pins {middle/counter_reg[15]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[15]/Q}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[15]_1} -source [get_pins {middle/counter_reg[15]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[15]/Q}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[16]} -source [get_pins {middle/counter_reg[16]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[16]/Q}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[16]_1} -source [get_pins {middle/counter_reg[16]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[16]/Q}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[17]} -source [get_pins {middle/counter_reg[17]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[17]/Q}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[17]_1} -source [get_pins {middle/counter_reg[17]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[17]/Q}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[18]} -source [get_pins {middle/counter_reg[18]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[18]/Q}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[18]_1} -source [get_pins {middle/counter_reg[18]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[18]/Q}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[1]} -source [get_pins {middle/counter_reg[1]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[1]/Q}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[19]} -source [get_pins {middle/counter_reg[19]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[19]/Q}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[19]_1} -source [get_pins {middle/counter_reg[19]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[19]/Q}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[1]_1} -source [get_pins {middle/counter_reg[1]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[1]/Q}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[20]} -source [get_pins {middle/counter_reg[20]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[20]/Q}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[20]_1} -source [get_pins {middle/counter_reg[20]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[20]/Q}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[21]} -source [get_pins {middle/counter_reg[21]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[21]/Q}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[21]_1} -source [get_pins {middle/counter_reg[21]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[21]/Q}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[22]} -source [get_pins {middle/counter_reg[22]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[22]/Q}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[22]_1} -source [get_pins {middle/counter_reg[22]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[22]/Q}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[23]} -source [get_pins {middle/counter_reg[23]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[23]/Q}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[23]_1} -source [get_pins {middle/counter_reg[23]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[23]/Q}]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[24]} -source [get_pins {middle/counter_reg[24]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[24]/Q}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[24]_1} -source [get_pins {middle/counter_reg[24]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[24]/Q}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[25]} -source [get_pins {middle/counter_reg[25]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[25]/Q}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[25]_1} -source [get_pins {middle/counter_reg[25]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[25]/Q}]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[26]} -source [get_pins {middle/counter_reg[26]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[26]/Q}]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[26]_1} -source [get_pins {middle/counter_reg[26]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[26]/Q}]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[27]} -source [get_pins {middle/counter_reg[27]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[27]/Q}]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[27]_1} -source [get_pins {middle/counter_reg[27]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[27]/Q}]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[28]_1} -source [get_pins {middle/counter_reg[28]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[28]/Q}]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[2]} -source [get_pins {middle/counter_reg[2]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[2]/Q}]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[2]_1} -source [get_pins {middle/counter_reg[2]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[2]/Q}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[3]} -source [get_pins {middle/counter_reg[3]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[3]/Q}]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[4]} -source [get_pins {middle/counter_reg[4]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[4]/Q}]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[5]} -source [get_pins {middle/counter_reg[5]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[5]/Q}]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[6]} -source [get_pins {middle/counter_reg[6]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[6]/Q}]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[7]} -source [get_pins {middle/counter_reg[7]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[7]/Q}]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[8]} -source [get_pins {middle/counter_reg[8]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[8]/Q}]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[9]} -source [get_pins {middle/counter_reg[9]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[9]/Q}]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[28]} -source [get_pins {middle/counter_reg[28]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[28]/Q}]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[29]} -source [get_pins {middle/counter_reg[29]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[29]/Q}]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[29]_1} -source [get_pins {middle/counter_reg[29]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[29]/Q}]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[30]} -source [get_pins {middle/counter_reg[30]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[30]/Q}]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[30]_1} -source [get_pins {middle/counter_reg[30]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[30]/Q}]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[31]} -source [get_pins {middle/counter_reg[31]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[2] [get_pins {middle/counter_reg[31]/Q}]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[31]_1} -source [get_pins {middle/counter_reg[31]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[31]/Q}]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[3]_1} -source [get_pins {middle/counter_reg[3]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[3]/Q}]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[4]_1} -source [get_pins {middle/counter_reg[4]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[4]/Q}]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[5]_1} -source [get_pins {middle/counter_reg[5]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[5]/Q}]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[6]_1} -source [get_pins {middle/counter_reg[6]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[6]/Q}]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[7]_1} -source [get_pins {middle/counter_reg[7]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[7]/Q}]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[8]_1} -source [get_pins {middle/counter_reg[8]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[8]/Q}]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/counter[9]_1} -source [get_pins {middle/counter_reg[9]/G}] -divide_by 2 -add -master_clock middle/FSM_onehot_current_state_reg_n_1_[4] [get_pins {middle/counter_reg[9]/Q}]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/r_value_int[1]} -source [get_pins {middle/FSM_onehot_current_state_reg[2]/Q}] -divide_by 2 [get_pins {middle/r_value_int_reg[1]/Q}]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/r_value_int[2]} -source [get_pins {middle/FSM_onehot_current_state_reg[2]/Q}] -divide_by 2 [get_pins {middle/r_value_int_reg[2]/Q}]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/r_value_int[3]} -source [get_pins {middle/FSM_onehot_current_state_reg[2]/Q}] -divide_by 2 [get_pins {middle/r_value_int_reg[3]/Q}]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/r_value_int[4]} -source [get_pins {middle/FSM_onehot_current_state_reg[2]/Q}] -divide_by 2 [get_pins {middle/r_value_int_reg[4]/Q}]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/r_value_int[5]} -source [get_pins {middle/FSM_onehot_current_state_reg[2]/Q}] -divide_by 2 [get_pins {middle/r_value_int_reg[5]/Q}]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/r_value_int[6]} -source [get_pins {middle/FSM_onehot_current_state_reg[2]/Q}] -divide_by 2 [get_pins {middle/r_value_int_reg[6]/Q}]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/r_value_int[7]} -source [get_pins {middle/FSM_onehot_current_state_reg[2]/Q}] -divide_by 2 [get_pins {middle/r_value_int_reg[7]/Q}]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name {middle/r_value_int[8]} -source [get_pins {middle/FSM_onehot_current_state_reg[2]/Q}] -divide_by 2 [get_pins {middle/r_value_int_reg[8]/Q}]
