# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/encoding_table_block/ip/encoding_table_block_auto_pc_0/encoding_table_block_auto_pc_0.xci
# IP: The module: 'encoding_table_block_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/encoding_table_block/ip/encoding_table_block_auto_pc_0/encoding_table_block_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'encoding_table_block_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: D:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/encoding_table_block/ip/encoding_table_block_auto_pc_0/encoding_table_block_auto_pc_0.xci
# IP: The module: 'encoding_table_block_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/TabledAsymetricNumeralSystems/KompresjaDanych/KompresjaDanych/KompresjaDanych.srcs/sources_1/bd/encoding_table_block/ip/encoding_table_block_auto_pc_0/encoding_table_block_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'encoding_table_block_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
